### ISSUE TITLE
Python MalmoPython DLL not found

### ISSUE THREAD

**Issue by likemike2** [Microsoft/malmo#157]
![image](https://cloud.githubusercontent.com/assets/20370521/16708191/3e21b7d0-45ea-11e6-8f3f-2d91fa78f79f.png)
I am trying to run the tutorial_1.py, but the DLL could not be found.

(I am quite new to python)

**Comment by mixtah** [comment]
I think you have python 32-bit installed.
Go to cmd, type just python and where it says the version, to the right it should also say whether it's for 32bit or 64bit. 
You'll need the 64-bit installation for it to work.

**Comment by bronydell** [comment]
![image](https://cloud.githubusercontent.com/assets/7874195/16713157/2c090a68-46a7-11e6-9a1a-f65f6ebf7fd2.png)
Same problem. Python x64. Windows 10

**Comment by bronydell** [comment]
![image](https://cloud.githubusercontent.com/assets/7874195/16713229/626d6a8e-46a9-11e6-9d4d-ea07be83ce24.png)
Same problem on Win10(Python x64!)

**Comment by geekstor** [comment]
This looks similar to #156. Have you tried the suggestions mentioned there? 

In particular, maybe first check the `PATH` variable and add the CodeSynthesis `bin64` and/or CodeSynthesis `bin` directories to the `PATH` (if they are not already present.)  I believe the default locations for these are `C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin64` and `C:\Program Files (x86)\CodeSynthesis XSD 4.0\bin` respectively. 

If something still doesn't work, you could try using <a href="http://www.dependencywalker.com"> Dependency Walker </a> as @timhutton mentions in the Gitter chat to identify the DLLs that seem to be missing, or, otherwise, certainly post a reply below.

**Comment by bronydell** [comment]
Great. Issue was in dependencies. Thanks

**Comment by likemike2** [comment]
@geekstor Adding the CodeSynthesis locations to `PATH `did work!

Thank you so much for your answer.
