### ISSUE TITLE
wrong port 

### ISSUE THREAD

**Issue by loordgek** [Microsoft/malmo#159]
i get his
`F:\downloads\Malmo-0.14.0-Windows-64bit\Java_Examples>java -cp MalmoJavaJar.jar;JavaExamples_run_mission.jar -Djava.library.path=. JavaExamples_run_mission
DEBUG: Sending MissionInit to 127.0.0.1 : 10000
Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.`

![help](https://cloud.githubusercontent.com/assets/4789835/16709843/a9541480-461c-11e6-9c38-ebac7f406778.png)
when i set it to 10000 i get the error
how do i fix that ?
and how can i check what is using port 10000 ?

**Comment by jaspercayne** [comment]
You can open Resource Monitor, go to the Network tab, and if you look at the TCP Connections and Listening Ports, that should give you a list of all ports in use on the machine.

**Comment by AlexanderPatrick** [comment]
I am having the same issue, but instead of trying to unblock port 10000, I was focused on trying to change the port the Agent tries to connect to. By default (https://github.com/Microsoft/malmo/blob/master/Malmo/src/ClientInfo.h#L29), it seems to try 127.0.0.1:10000 three times then errors out, but it seems there is no option for specifying what port to use so I could change it to use 10001 like the mod is listening on.

**Comment by timhutton** [comment]
You can ask the AgentHost to connect to a different client using a ClientPool. See `Python_Examples/tabular_q_learning.py` for an example.

**Comment by loordgek** [comment]
it was for me utorrent that was using port 10000

**Comment by AlexanderPatrick** [comment]
Yep, uTorrent was using my port 10000 as well.

On 10 Jul 2016 11:25 a.m., loordgek <notifications@github.com> wrote:

it was for me utorrent that was using port 10000
