### ISSUE TITLE
Severe framerate issue when running from launchClient.bat

### ISSUE THREAD

**Issue by einsteinsci** [Microsoft/malmo#186]
While running a mission (or when in a world created/opened from the client directly), the framerate drops to about 1-4 FPS, even in the first tutorial. This makes it extremely difficult to see what the agent is doing. Anything more than the simplest of agents will cause repeated `java.lang.OutOfMemoryException` crash reports from the client.

My computer is fairly high-end, enough to run Minecraft with Feed the Beast modpacks (some with over 150 mods) at 60 FPS. Here are my specs:

OS: Windows 10 Home (x64), Version 1511, Build 10586.494, Update KB3172985
Processor: Intel Core i5-4570 @ 3.20GHz
RAM: 16 GB DDR3
GPU: NVidia GeForce GTX 760

Is there a way to raise the max memory via JRE arguments for starting up the client (from 1.6 GB)? I assume doing so could improve the situation.

EDIT: There is a workaround by launching via the Minecraft launcher. However, since the tutorial suggests running via launchClient.bat, this is still an issue.

**Comment by DaveyBiggers** [comment]
Hi @einsteinsci, sorry you are having issues. Can I ask whether you installed a pre-built release, or built from source?
A few things to try:
Minecraft should be starting with more than 1.6GB - can you check in your `malmo\Minecraft\build.gradle` file for a line like the following:

`exec.jvmArgs(["-Dfml.coreMods.load=com.microsoft.Malmo.OverclockingPlugin","-Xmx2G"])`

You could try upping the 2G to 3 or 4G, though I'm not sure why your system would require extra memory when 2G seems to work elsewhere. Are you running Malmo alongside other mods?

You could also try adding the exact JVM arguments that the Minecraft Launcher uses (hit Edit Profile and the JVM arguments are at the bottom of the dialog box - eg mine appear to be `-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M`)

If that doesn't help, could you paste in the log you get from Minecraft - eg the console output of launchClient.bat - maybe the Malmo mod is doing something strange.

Finally, if you've already got the forge binaries installed (which I assume you must have, since you have all those modpacks) then you should indeed be able to run the Malmo mod from the Minecraft launcher by building/installing it in the usual way. Please note that we didn't really design the Malmo mod to play nicely with other mods though, and it hasn't been tested against anything except vanilla Minecraft and the particular version of Forge we've been using (currently 1.8-11.14.3.1543).

**Comment by einsteinsci** [comment]
I've been using a pre-built release. However, the source is included, and it looks like it runs `gradlew build` every time `launchClient.bat` is run anyway, so I'm not sure if that makes much of a difference.

Upping the ram in `build.gradle` to 4GB somehow fixed the whole thing. Perhaps when it was lagging Java wasn't able to increase the memory from the minimum while gradle was running?

**Comment by DaveyBiggers** [comment]
Out of interest, what are the JVM settings in your Minecraft launcher? If that's also set to 4GB then it would explain why running from the launcher worked. If it's something smaller, like 1.6GB, then there must be something else going on...

**Comment by einsteinsci** [comment]
I tested it with 1600M in the launcher, and it was lagging severely (although slightly less than the original issue). I was getting between 3-15 FPS in short bursts, alternating with 1-second periods of 0 FPS. This happens even after the world has fully loaded.

**Comment by DaveyBiggers** [comment]
Strange. The defaults are fine on our machines, we don't have any issues with lag. Your Minecraft log might show something, if you paste it here. Just to be clear - does this happen when running without any other mods installed?

**Comment by einsteinsci** [comment]
This was without any other mods. Malmo is the only mod installed.

**Comment by DaveyBiggers** [comment]
Am going to close this since we've been unable to reproduce it, and @einsteinsci has a workaround. Please feel free to reopen if it's still causing problems.

Brief thought - what do you have your render distance set to?

**Comment by einsteinsci** [comment]
That's always been at Far (16 chunks), but all the lag seemed to come from the tick and unspecified on the lagometer, not from rendering.
