### ISSUE TITLE
drawing_test.py agent gets stuck in a block

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#195]
Run drawing_test.py - the agent starts off stuck up to the waist in wool.
This doesn't seem to be a simple problem with the position coords - they appear to be correct. It seems as though the agent might be falling at the start of the mission - the menger sponge the agent should be standing on takes too long to get drawn, and the agent has time to fall before it appears.

If so, this is a fairly serious issue that we should look into.

**Comment by timhutton** [comment]
I've modified drawing_test.py so that when run as an integration test it fails if the player has sunk up to their waist in wool. Currently it is failing reliably.

Code in WaitingForAgentsEpisode.initialisePlayer() uses spectator mode to avoid falling before the mission starts. But possibly that is client-only and the server needs to be told?

The problem is greatly reduced if in drawing_test.py you start the player at y=83 instead of y=86. But it is not completely eradicated.

The problem seems to go away if the world is not reloaded.

**Comment by timhutton** [comment]
In 8c9ef88b I've changed the y-position of drawing_test.py so the player doesn't start out falling. This avoids the problem of ending up in wool almost all of the time.

Reducing this issue to P3 because:
1) For now we're not interested in supporting the use-case of the player starting off falling. 
2) The case of the player sinking into their floor when given the correct y is pretty rare.
