### ISSUE TITLE
feature request: ability to parametrize the number of degrees of a turn in discrete action space

### ISSUE THREAD

**Issue by lydiatliu** [Microsoft/malmo#213]
or allow 45 degree turns. @katja-hofmann

**Comment by DaveyBiggers** [comment]
What happens if you turn 45 degrees and then try to move forward one block? I guess it just allows us to have an 8-connected gridworld instead of a 4-connected one (in which case we should probably also add movenortheast, movesouthwest etc.etc. commands).
But it wouldn't make sense to allow anything finer than 45 degree increments.

**Comment by timhutton** [comment]
Decided we didn't want this. Comment if you disagree.
