### ISSUE TITLE
Add API function for list of allowed commands with number of parameters

### ISSUE THREAD

**Issue by geekstor** [Microsoft/malmo#217]

**Comment by timhutton** [comment]
When loading missions for agents to run, it is sometimes important to know what actions the mission permits. This happens when the agent is able to cope with both discrete and continuous actions, for example. We see this in the human action component and the rl-framework.

For discrete commands it makes sense to have an API function that returns a list of the allowed commands: { "move 1","turn 1", ... }. For continuous actions this is less obvious, but maybe a list of the verbs is useful: { "move", turn", ... }

**Comment by timhutton** [comment]
Suggestion: 
```
vector<string> MissionSpec::getListOfCommandHandlers() const;
vector<string> MissionSpec::getAllowedCommands(const string& command_handler) const;
```
