### ISSUE TITLE
Multi-agent missions currently require one Minecraft login per agent

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#225]
This article suggests that we may be able to work around this:
http://www.howtogeek.com/239649/how-to-play-multiplayer-lan-games-with-a-single-minecraft-account/

Since we rely entirely on the integrated server at the moment, all our multi-agent setups use the LAN, which might mean we don't need full authentication. This would be a big help!

**Comment by tnarik** [comment]
Hi,

I was hacking around and managed to get two agents running with a single set of credentials, by tweaking

`private static boolean forceSessionUpdate(YggdrasilUserAuthentication auth)` in the `AuthenticationHelper` class, essentially setting a different `username` for the `Session`, while configuring the same set of credentials for all ports in the Mod.

Still need to get my head around it because I am hardcoding the value and on subsequent runs only that is used (which fails), but on a first run I got agents with the original username and the hardcoded one. Plus something else might be not working correctly.

**Comment by tnarik** [comment]
Got a version running from my forked code, where the player names are dynamically generated (similarly to the way players are named without authentication). The `two_diggers.py` example runs correctly with that setup (building from code, as 1.7.0 seems to have issues with multi-agent rewards).

Will try to make the names cleaner (appending the agent names to the username maybe?) and produce a pull request.

**Comment by tnarik** [comment]
Created pull request #378.

**Comment by tnarik** [comment]
New pull request #391.

**Comment by DaveyBiggers** [comment]
Finally closed in #429.

**Comment by DaveyBiggers** [comment]
(Many thanks to @tnarik for help!)

**Comment by JustinFletcher** [comment]
Awesome - I had to pause my work until this was resolved. I'm looking forward to getting back to it. Thanks, @DaveyBiggers and @tnarik!

**Comment by tnarik** [comment]
Thanks, @DaveyBiggers :D
