### ISSUE TITLE
Random seed in ALE cannot be set

### ISSUE THREAD

**Issue by katja-hofmann** [Microsoft/malmo#254]
The code in https://github.com/Microsoft/malmo/blob/63fbaad6501905a6667e393d4d6318a6107be7fe/Malmo/src/ALEAgentHost.cpp#L83 suggests that the same seed (123) is used on every run using the ALE environment. This should be set (a) to a different seed on each run, or (b) to a user-provided seed. Ideally, both should be possible.

**Comment by DaveyBiggers** [comment]
Have added `ALEAgentHost::setSeed(int)`.
(Not ideal, since it breaks the whole keeping-the-agent-host-inferfaces-the-same paradigm, but then, that never made much sense anyway.)

Calling `setSeed(123)` will reproduce the previous behaviour, which was always setting the seed to 123.
Calling `setSeed(0)` will cause the ALE to seed from the current time each go.
