### ISSUE TITLE
Command "setYaw" does not change movement direction

### ISSUE THREAD

**Issue by salaniz** [Microsoft/malmo#255]
Using the absolute movement command "setYaw" changes the view orientation of the player but not his actual body orientation. Sending the "move 1" command afterwards (discrete or continuous) makes the player move into the yaw direction that was present previous to "setYaw".

In the discrete scenario the player moves sideways/backwards and in the continuous case the player changes back to the original yaw orientation.

**Comment by DaveyBiggers** [comment]
The absolute movement commands don't currently play well with the continuous movement commands, which take control over the yaw/pitch and don't relinquish it easily... this is certainly something that should be improved.

In the discrete case, the setYaw command doesn't make a whole lot of sense unless it is restricted to multiples of 90 degrees, since discrete motion assumes a 4-connected grid and only allows the player to move one square at a time. There is a discrete turn command which can be used instead, which turns the agent by +/- 90 degrees.
