### ISSUE TITLE
MissionRecordSpec problem

### ISSUE THREAD

**Issue by WXFMAV** [Microsoft/malmo#258]
we noticed that the output observation stream of agent is some std::strings like 
**TimestampString: 2016-Aug-04 13:21:33.642928, {“DistanceTravelLED”：22612，“TimeAlive":28707,"Mobskilled":0,"DamageTaken":0,"Life":20.0,"Score":0,"Food":20,"XP":0,"IsAlive":true,"Air":300,"XPos":-7.839998131964445,"YPos":227.0,"ZPos":-7.428731975283811,"Pitch":-0.45,"Yaw":242.88135}**
among which the date string **2016-Aug-04 13:21:33.642928** is not so easy to be transformed into timestamp such as an integer with type of **__int64** .
we want to know that 
(1) if the obeservations string is the only way we get agent status(such as position ,attitude)? or can we refer to other API that we can get this variable directly?
(2) Is there already a well-managed library that we can refer to decode this string ?
thanks so much.

**Comment by DaveyBiggers** [comment]
Hi @WXFMAV - all observations, rewards and frames are time-stamped using boost::posix_time. This time-stamp is then exposed via the API in a format appropriate to the language being used - for example, in Python, it is exposed as a python DateTime object. The time-stamp text you are seeing is just a nicety that happens when you convert the time-stamp value to a string - you should be able to deal directly with the value and ignore the string.

The observations are the only way of getting the agent's status, and they are returned as JSON. You should have no difficulty finding a well-managed JSON library for the language of your choice.

**Comment by DaveyBiggers** [comment]
(Note that all the information saved in the recording is available to the agent while it is running - look at agent_host.getWorldState()...)

**Comment by WXFMAV** [comment]
I got it, thanks so much.

**Comment by DaveyBiggers** [comment]
No worries.
