### ISSUE TITLE
Is there python3 support?

### ISSUE THREAD

**Issue by okdshin** [Microsoft/malmo#271]
I want to run malmo with python3 rather than python2 because the library of ML that I'll use does not support python2.
Is there python3 support?

**Comment by timhutton** [comment]
Hi @okdshin. We don't currently have support for Python 3. It is something we will try at some point, if there's demand for it. Boost.python has support for it.

If you're interested, you could give it a go yourself, by building Malmo from source. Some pointers:
- You'd need to change the root CMakeLists.txt [here](https://github.com/Microsoft/malmo/blob/master/CMakeLists.txt#L125) to look for Python 3.
- The samples would need to be updated.

Let us know if you make any progress.

**Comment by cld5070** [comment]
I'm interested in this as well (both as a research tool and to use Malmo in a CS course project.
Please post if you have success (as will I)

**Comment by okdshin** [comment]
Thanks @timhutton and @cld5070.
I’ll think about it and I'll post the result if it success.

**Comment by cld5070** [comment]
@okdshin Just an FYI, this works fine w/ a few things changed in the build/setup process:
You'll need to look for *Python 3.5* (cmakelists.txt currently looks for Python 2.7)
use  _brew install boost-python --with-python3 without-python_ 
any (obviously) change any python files to work w/ Python3 libraries (e.g., the sample files)

**Comment by okdshin** [comment]
I found the way.

```
brew uninstall boost-python # if needed
brew install boost-python --with-python3 without-python
cmake .. -DUSE_PYTHON_VERSIONS=3.5 \
  -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m/libpython3.5m.a \
  -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/include/python3.5m
```
I have not modified Python_Examples yet, but we can run malmo with Python3 anyway.

**Comment by tambetm** [comment]
I've been able to successfully compile Malmo on Ubuntu 14.04 against Python 3.4. The `cmake` command line was like this:

```
cmake .. -DUSE_PYTHON_VERSIONS="3.4" -DINCLUDE_CSHARP=no -DINCLUDE_LUA=no
```

Unfortunately when I try to import MalmoPython, I get following error:
```
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from minecraft_py import MalmoPython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0: undefined symbol: PyClass_Type
```

I'm assuming that it decided to link against Py2.7 libboost package, while both 2.7 and 3.4 packages are available on my system:
```
$ ls -1 /usr/lib/x86_64-linux-gnu/libboost_python*
/usr/lib/x86_64-linux-gnu/libboost_python.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python-py34.a
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_python.so
```

Can I somehow force Malmo to link against Py3.4 version of libboost?

**Comment by okdshin** [comment]
Hi @tambetm.

I bumped into the same error on Ubuntu16.04. I couldn't find how to install boost-python with python3 via apt-get. So I built boost from source by myself.
http://www.boost.org/

In the root of boost source directory, I ran below command. You can modify it.
```
./bootstrap.sh --with-python=python3 --with-python-version=3.5 --with-python-root=/home/okada/.pyenv/versions/3.5.2
```
 Maybe python3.4 is OK but for 3.5, I had to run `ln -s python3.5.2m python3.5.2` to hide obstacle `m`.

Then you have to change BOOST_ROOT.
https://cmake.org/cmake/help/v3.0/module/FindBoost.html

Good luck!

**Comment by tambetm** [comment]
I was able to compile Malmo successfully for Python 3 on Ubuntu 16.04 using preinstalled boost. The trick was following:

```
cd /usr/lib/x86_64-linux-gnu/
ln -sf libboost_python-py35.so libboost_python.so
ln -sf libboost_python-py35.a libboost_python.a
```

I'm not sure what repercussions that might have, because I did my compilation inside [Docker container](https://github.com/tambetm/minecraft-py3/blob/master/Dockerfile).

The precompiled version for Ubuntu 16.04 is also available here:
https://github.com/tambetm/minecraft-py3

**Comment by mfuntowicz** [comment]
On windows, need to build boost from scratch, by adding a file user-config.jam in the root directory with :
`using python : 3.4 : /path/to/python/dir`

You need to build Boost.Build : 
```
bootstrap.bat

Building Boost.Build engine with toolset msvc-12
Unicode/ICU support for Boost.Regex?... /usr
Backing up existing Boost.Build configuration in project-config.jam.3
Generating Boost.Build configuration in project-config.jam...
```

After what you should be able to compile boost by running : 
`.\bjam.exe --adress-model=64 --with-python variant=release link=static --build-type=complete`

FInally you can follow compilation steps indicated in the Wiki, just take care about the -DUSE_PYTHON_VERSIONS variable in cmake to indicate the version of Python you want to compile with.

**Comment by nikitakit** [comment]
I have had success getting malmo to run with anaconda python3 on Mac, roughly following the instructions by @okdshin 

However, I have found it essential to change the PYTHON_LIBRARY definition to point to `libpython3.5m.dylib` instead of `libpython3.5m.a`. (The version that uses `.a` gave me "Segmentation Fault: 11", which took a long time to debug. I suspect that using `.a` leads to the creation of a statically linked copy of libpython that is distinct from the libpython actually used by the python interpreter.)

**Comment by floringogianu** [comment]
I was able to compile and run Malmo with Anaconda's python3.6 distribution on Ubuntu 17.04. I had just to install `boost-anaconda` and make sure the compiler sees it (so no Boost building required). Also I used `update-alternatives` to set `gcc-4.9` instead of the one Ubuntu currently ships with (`6.3`).

```
conda install -c ananconda boost=1.61.0
export BOOST_ROOT=/path/to/anaconda3
```

And then just:

```
export MALMO_XSD_PATH=/path/to/malmo/Schemas

cd malmo
mkdir build
cd build

cmake .. -DUSE_PYTHON_VERSIONS=3.6 \
-DINCLUDE_LUA=OFF -DINCLUDE_JAVA=OFF -DINCLUDE_TORCH=OFF -DINCLUDE_CSHARP=OFF

make install
```

**Comment by pablocastilla** [comment]
+1 to migrate to python 3. I want to use Tensorflow and it needs python 3.5.

I will try following your instructions, thanks!

**Comment by pablocastilla** [comment]
Hi!

I am new to all of this cmake, boost and so on stuff. Under windows 10 I am trying to build malmo using anaconda boost as @floringogianu and I have the following error. Does anyone know how could I solve it?

Thanks os much!

C:\Users\Pablo\Source\Repos\malmo>cmake . -DUSE_PYTHON_VERSIONS=3.5 -DINCLUDE_LUA=OFF -DINCLUDE_JAVA=OFF -DINCLUDE_TORCH=OFF -DINCLUDE_CSHARP=ON
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1842 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.61.0

  Boost include path: C:/Program Files/Anaconda3/Library/include

  Could not find the following static Boost libraries:

          boost_zlib

**Comment by Brigadirk** [comment]
I am using Mac and I've tried to build using python using both @okdshin and @floringogianu methods above. But I'm getting the following error (so, not unlike @pablocastilla, but with boost_python instead) :

Unable to find the requested Boost libraries.

  Boost version: 1.61.0

  Boost include path: /Users/Dirk/anaconda3/include

  Could not find the following Boost libraries:

          boost_python

I've tried setting BOOST_ROOT to the boost path, as well as setting the LIBRARYDIR to the anaconda include folder, but neither approach seems to change anything about the error.

Anyone know how to solve this (I assume the solution is analogous to @pablocastilla 's problem).

Thanks

**Comment by kkjh0723** [comment]
I'm using Anaconda python 3.6 in Ubuntu 14.04. While I'm following instructions by @floringogianu, I got following error,

    Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
      (Required is at least version "3.6")
    Call Stack (most recent call first):
      /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 
    (_FPHSA_FAILURE_MESSAGE)
      /usr/share/cmake-3.2/Modules/FindPythonLibs.cmake:205 
    (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:139 (find_package) 

It seems related to `libpython` but how can I link `libpython` in `~/anaconda3/lib` ?

**Comment by kkjh0723** [comment]
I followed instruction by @floringogianu after some modification and it seems I finished until `make install` without an error.
Then how can I check it is installed correctly?  It seems `Python_Examples` are not running because of different syntax. And I cannot import 'MalmoPython' also... 
It means my installation is something wrong?

**Comment by DaveyBiggers** [comment]
@kkjh0723 the Python examples were all written in Python 2, but you should be able to modify them to work with Python 3 syntax.

**Comment by Phantomb** [comment]
Another request for Python 3.5 and beyond support, specifically for TensorFlow here!

I tried building Malmo myself trying both @mfuntowicz , and @floringogianu 's instructions, but got stuck on various points:

- Building boost does not seem to build with zlib
- Running `xsltproc` throws an popup error window saying it can't find 'libwinpthread-1.dll'
- cmake could not find boost_zlib (same issue as @pablocastilla )

I'm on Windows 10, Python 3.6. Trying with latest release of Boost (1.64.0) and zlib (1.2.11).

Can anyone help me figuring out what to do?

**Comment by DaveyBiggers** [comment]
Status update: we've futurised the Malmo samples so that they should work with python2 and python3, and from now on (starting with 0.31.0) we'll be releasing py3 builds as well as py2 builds. I'm currently in the process of pulling all the information in this thread together, and will update the documentation accordingly, after which I'll close this issue.

**Comment by Phantomb** [comment]
Awesome! I'll keep an eye on this and try it out soon.

**Comment by Phantomb** [comment]
I just tried it out and it worked flawlessly out of the box except for these two things:

1. I initially received it still received a version `0.30` from the schema mission XSD instead of the required 0.31. I found this strange, since the version specified in all schemas was `0.31`, and my `MALMO_XSD_PATH `was correctly set to the new version. I managed to fix this by setting the path to a random empty folder instead, after which I didn't get that error and it was able to run. After this successful run, I changed the path back to the schemas folder, and it was still able to run without throwing the error.
2. The `tabular_q_learning.py` test had trouble the string formatting in line 288: `color_string = '#{:02x}{:02x}{:02x}'.format(255-color, color, 0)`. This was apparently due to color being a float where it expected an int. The error was resolved when I explicitly casted color to an int.

Would you like me to make separate issues for both problems I encountered? Would you like me to submit a pull request for the edit to `tabular_q_learning.py`?

**Comment by laysdra7265** [comment]
That wired,when the problem appearing,I found the code in the "Minecraft\src\main\java\com\microsoft\Malmo\Client" is old version,and i spent whole day to recompile my self the new version mod code.
And now i recheck the zip i download that time,the source code in is the correct version???how??
well I don't know how did it happen,maybe something goes wrong when my first installed,the old code overwrite the file?I might accident overwrite the code for some reason that i didn't notice.
