### ISSUE TITLE
Mission string not checked for equality in multi-agent missions

### ISSUE THREAD

**Issue by timhutton** [Microsoft/malmo#3]

**Comment by DaveyBiggers** [comment]
Reopening. I've had to disable this check since it was returning a false negative in the case of MultiMaze.py, and probably many more multiagent missions.

There are a few reasons for this:
1) The MazeDecorator writes the agent's start position directly back into the Mission object, so the XML used in the comparison already differs from the original. (There may be other issues along these lines.)
2) The XSD-generated java classes use lazy-initialisation in some of the getters - i.e. calling "getColour" results in a collection object being created if it didn't already exist. These (empty) objects then get written back into the XML upon serialisation.

I guess the easiest fix would be to take a copy of the virgin XML before it's used, and keep that for comparisons.

**Comment by DaveyBiggers** [comment]
Some more thought is needed here - do we even need to do this check? Do we want to force all agents to use the same XML...? Am closing this and opening a separate issue to track the bigger picture.
