### ISSUE TITLE
Why time.sleep(0.5) is needed after agent.run() in tabular_q_learning.py?

### ISSUE THREAD

**Issue by okdshin** [Microsoft/malmo#307]
I have some questions about below line.
https://github.com/Microsoft/malmo/blob/672a68971f88f6cef39642825ebccc1c261977fd/Malmo/samples/Python_examples/tabular_q_learning.py#L410
- What is this sleep for?
- Where does "0.5" come from?
- Can I remove it?

**Comment by DaveyBiggers** [comment]
It's there to give the mod time to reset. When the mission ends, the mod first sends a MissionEnded message to the agent host, and then it does some housekeeping before returning to the dormant state, ready for the next mission.
During this housekeeping stage, attempts to start a new mission will be rejected, so we wait half a second.

A better solution might be to have the mod return a "try again later" message during this housekeeping stage, rather than the "busy" message it currently returns. Then the agent code (or perhaps our AgentHost code) could respond to that and wait. But for now, the time.sleep() is a simple solution.

**Comment by okdshin** [comment]
Thanks for your reply.
Without that time.sleep(0.5), my script occurs segmentation fault error randomly.
I'm now trying to reproduce it with minimum codes. When I catch it, I will post it......

**Comment by DaveyBiggers** [comment]
Am assuming this is no longer an issue, and closing. Please reopen if you manage to reproduce it. Cheers.
