### ISSUE TITLE
Integrate build battle mod code

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#337]

**Comment by salaniz** [comment]
I have implemented the build battle code in my Malmo installation, however the `BlockEvents` do not seem to trigger correctly. It uses `PlaceEvent` and `BreakEvent` and I can get it to work when I use the "Human Action Component" by issuing the commands myself. Once I let my agent perform the actions `use 1` and `attack 1` (I use the discrete actions), the events do not seem to trigger and I get no reward. Likewise, since the `BlockEvents` aren't triggered in agent mode, the agent is able to destroy and place blocks outside the building area whereas I, using the HAC, cannot.

**Comment by DaveyBiggers** [comment]
@salaniz - I've just created a PR (#375) with some updated build battle code, based on @geekstor's original code. It's not been thoroughly tested yet but hopefully it will resolve the issues you mention. (Though building outside the build area is currently allowed, provided it's not within the specified original area.)

**Comment by salaniz** [comment]
@DaveyBiggers, @geekstor - thanks a lot for the code and the PR! Unfortunately, this code does not resolve my issue. The problem persists that I am getting the reward in HAC mode, but not in agent mode.

Does anyone of you have a running example that it works with?

**Comment by salaniz** [comment]
@DaveyBiggers I checked out your latest commits for the build battle code. Thanks a lot for the work you put in. The build battle code fixed my problem now. Frankly, I think I didn't test against my problem thoroughly enough on the initial PR code so ignore my previous comment.

The code helps a lot and the example is amazing!
