### ISSUE TITLE
FileWorldGeneratorImplementation.createWorld test for file loading returns false negative

### ISSUE THREAD

**Issue by DaveyBiggers** [Microsoft/malmo#342]
This means the world is loaded successfully, but the mod thinks it wasn't.
(From #332).

Three things:
- The code needs to be fixed!
- We should have an integration test for this (this will be a little tricky, since it will require a big old saved world file - perhaps the test can create this itself?)
- The mod doesn't respond graciously to the error, leaving the agent host stuck waiting for mission start.

**Comment by TGlas** [comment]
I have a follow-up on this, or rather on #332. I have now written some simple file management code that should allow me to continue with a previously played world exactly from where I was. At the end of the mission I move the world to a different directory, which is then provided to the FileWorldGenerator. If the world does not exist yet then it is created with the DefaultWorldGenerator. However, even a world created this way is rejected by the loader. I can confirm that I can play that very same world in single player mode in Minecraft 1.8.

Now it turns out that this is all caused by be renaming the directory containing the world. Well, I don't like the clumpsy "10000_[unique-di]" names, hence I renamed it when moving the directory. If I don't rename the directory then everything works fine. So this whole issue may be caused by a check demanding that the directory name coincides with the world name, which seems to be stored independently somewhere (otherwise the client could not display that cryptic name after renaming the directory, which it does).

I see two ways out: demand that directory and world name coincide, and throw a helpful error message if this is not the case. Or ignore the discrepancy, which apparently does not keep the game from running normally. Of course, in the long run there should also be an option for continuing with and existing world, but that's an independent issue.
