### ISSUE TITLE
Suggestion: The order of observed grids should be changed considering the agent's yaw

### ISSUE THREAD

**Issue by okdshin** [Microsoft/malmo#347]
The order of observed grids given by malmo is independent of the agent's yaw. It's inconsistent with the fact that the taken images depend on the yaw.
Now I am re-ordering the grids by using a lookup table. It's annoying.

**Comment by DaveyBiggers** [comment]
I think the current design, while annoying, is cleaner. What does it mean if the agent's yaw is set to 45, for example? I don't consider this to be inconsistent with the POV images, since they are two very different representations of the world data. And it is entirely consistent with the `DrawingDecorator` co-ordinate system.

If you're using python, numpy apparently has methods for easily reordering the grids - @katja-hofmann can give you more information on this.
