### ISSUE TITLE
Malmo::MissionSpec interface is incomplete

### ISSUE THREAD

**Issue by TGlas** [Microsoft/malmo#354]
I was just trying to get rid of my mission.xml and to do the same setup using methods of the MissionSpec class. However, it turns out that quite a few options are only available via XML setup. For example, the class does not support loading a world from disk, or observing the "ray" or the entities. I cannot see corresponding methods in the 
[documentation](http://microsoft.github.io/malmo/0.17.0/Documentation/classmalmo_1_1_mission_spec.html) and also not in the C++ headers, so I conclude that they are missing.

Is this intended, i.e., should the programmatic interface be restricted to "simple" cases, or will this be fixed? For now my workaround is to assemble the XML string in my program, however, I'd prefer to do things through a proper interface.

**Comment by salaniz** [comment]
It is like this by design. That's what @DaveyBiggers told me on [Gitter](https://gitter.im/Microsoft/malmo?at=57ceab6bfe284f6c302b96ce) when I had a similar question recently.

**Comment by DaveyBiggers** [comment]
Yes, we were never planning to have a "full" API implementation. The XML _is_ the "proper interface" - it is significantly more concise than using the API, easier to read (since it's hierarchical, and therefore groups all related concepts together, whereas API code can be spread around), and it's completely language-independent (so the complete mission setup can be shared between researchers who are using different languages). But, most importantly, XML is also the underlying implementation - the API is just a layer on top. This means that the API effectively masks details of what is happening, and also has to make interpretive choices for the user which may or may not be intuitive. (For example, what should happen if a player calls `setWorldSeed` before calling `createDefaultTerrain`?) Some concepts simply don't map cleanly from the XML format to the API, so trying to support the full spec would result in an API that is very complicated to implement, a nightmare to maintain, and would potentially expose the user to a whole raft of difficult to diagnose gotchas and gremlins.

For these reasons, we've restricted the API to simple cases, and recommend that people use the XML for anything more detailed. And with the excellent string handling routines of most scripting languages these days, it's a fairly easy matter to build the XML programmatically if needed - most of the python samples do something along these lines.

**Comment by TGlas** [comment]
Fine. Thanks for elaborating on this. From a programmers perspective this is somewhat unexpected (I am too much used to designing APIs in the first place and not file formats), but it makes sense with your explanation. In the meantime I have switched to the approach of generating XML anyway.
