### ISSUE TITLE
Chat observations not working?

### ISSUE THREAD

**Issue by TGlas** [Microsoft/malmo#360]
I specify `<ObservationFromChat/>` and `<ChatCommand/>` in my XML specification. I receive chat observations of the form `"Chat":[]`.

The problem is that the array is always empty. I cannot see the countdown messages sent by the server, nor do I see echos of my own messages sent throught the `chat` command. All of these messages appear in the game window, therefore I was expecting to observe them, too. Is this intended behavior or maybe a bug?

**Comment by DaveyBiggers** [comment]
The timer countdown messages aren't sent through the chat channel, they are printed directly to the screen, so I wouldn't expect them to appear in the chat observation. If this behaviour is something you'd like to see changed, feel free to add a feature request, but I think it's good to avoid polluting the chat with the timer messages.

As for not being able to see echoes of your own messages, I've not been able to reproduce this behaviour. "Works for me", as they say... is it still an issue with your code? If so, we'll need some more details in order to track it down.

**Comment by TGlas** [comment]
Thanks for the clarification on the countdown. I'll close this for now.
