### ISSUE TITLE
Python examples will not run. ImportError: DLL load failed: The specified procedure could not be found

### ISSUE THREAD

**Issue by jwflammer** [Microsoft/malmo#387]
I cant get python or any examples to run, I have gone threw all the steps for windows 10 64-bit dependencies. Still nothing. I think I have all my paths correct, I have everything installed. 

any help would be much appreciated. 
Thank You.

**Comment by tikikevin** [comment]
I am having the same issues. Double checked versions: Windows 10 64-bit, Python 2.7 64-bit, all the proper versions of the dependencies, and all the paths set correctly. I'd really like to get this running for an educational demo.  Thanks!

**Comment by DaveyBiggers** [comment]
It looks as though the 0.18.0 Windows release was somehow accidentally built against the _debug_ version of the Microsoft VC++ redist. I'm looking into how this happened (probably just a stupid mistake on my part) and hopefully there will be a fixed build uploaded in the next hour or so.

NB: The Python import error is singularly unhelpful. If you try to run the C++ example instead, the error message is more useful: "The program can't start because MSVCP120D.dll is missing from your computer."

**Comment by DaveyBiggers** [comment]
Right, this was indeed caused by the debug mixup. I've removed the faulty build and uploaded a new one here: https://github.com/Microsoft/malmo/releases/download/0.18.0/Malmo-0.18.0-Windows-64bit.zip

Many apologies for this mistake, and thank you both for taking the time to report it.
