### ISSUE TITLE
Ensuring a command has been received / performed

### ISSUE THREAD

**Issue by JannerM** [Microsoft/malmo#405]
I noticed that in the Torch example mission, there is a pause of 0.5 seconds after every command sent. I’m trying to avoid these long pauses, so I modified the main loop of `run_mission.lua` to look like:

```
while world_state.is_mission_running do
    -- choose action
    action_ind = (action_ind % #actions) + 1
    action = actions[action_ind]

    io.write(action .. '        ')

    -- send action
    agent_host:sendCommand( action );

    world_state = agent_host:getWorldState()

    -- stall until frame and observation received
    local received_frame = false
    local received_obs = false
    while not (received_frame and received_obs) do 

        if world_state.number_of_video_frames_since_last_state > 0 then
            received_frame = true
            frame = world_state.video_frames()
        end

        if world_state.number_of_observations_since_last_state > 0 then
            received_obs = true
            obs = json.decode(world_state.observations().text)
            z = obs['ZPos']
        end

        world_state = agent_host:getWorldState()
    end

    print(z)
end

```

I was hoping that a new observation and frame would not be received until the action had been performed, but this does not appear to be the case. I’m having the agent move forward and backward, and the output looks like this: 

```
<action>	<ZPos>
move -1        1.5
move 1         1.5
move -1        1.5
move 1         1.5
move -1        0.5
move 1         0.5
move -1        1.5
move 1         1.5
move -1        0.5
move 1         0.5
move -1        1.5
move 1         0.5
move -1        0.5
move 1         0.5
```

When there is a pause of 0.5 seconds between actions, the output is (most of the time) what you’d expect:
```
move -1        1.5
move 1         0.5
move -1        1.5
move 1         0.5
move -1        1.5
move 1         0.5
...
```

Is there a check I can perform on the world state, something analogous to `number_of_video_frames_since_last_state`, that ensures previous commands have been performed?

It looks like this issue was discussed a bit [here](https://github.com/Microsoft/malmo/issues/130) already, which seemed to imply that as long as commands are sent slower than the Minecraft tick speed, I should be fine. I tried lowering the MsPerTick value in the XML, but this did not seem to solve the problem.

**Comment by DaveyBiggers** [comment]
Yes, I'm afraid this is a common area of difficulty. Unlike the ALE, and many other RL experimentation platforms, Malmo can't, and doesn't try to, enforce rigid synchronisation between actions/states etc. Minecraft, for all its blockiness, doesn't really operate in a discrete way, either in terms of space or in terms of time. Actions may take varying amounts of time to take effect, and observations are generated asynchronously. It's a pain, but it's part of the richness that makes Minecraft such an interesting research arena...

That said, the situation isn't entirely hopeless. There are better solutions than simply waiting half a second between each action (which is far from ideal!)

We have an `observationFromRecentCommand` handler, which spits back the commands received as an observation - though all this really tells you is that the Mod has received and _begun_ to act on the command - it doesn't guarantee that the effects of the command will show up in the next observation.

For something more reliable, take a look at robust_frames.py, which attempts to obtain robust frame-action pairs. The basic approach is to wait for an observation which matches the expected behaviour. In our own research code we do something similar. It's not ideal but it helps.

(Tabular_q_learning.py also does something similar, to maintain state-action pairs.)

Longer term, we have an issue covering this - #301 - which will hopefully considerably simplify matters. The basic idea would be to make sure each command handler knows both how to apply its command, _and_ check for the command's completion. The platform could then optionally wait for a completion signal for each command before returning any more state information.

Regarding the MsPerTick value, some commands just take more than one tick to take effect and be reported - regardless of how fast the ticks are. But the issue you linked to is still relevant, since sending commands faster than the game tick will certainly cause problems.

I hope that's of some help - let us know if you have any further questions.

**Comment by JannerM** [comment]
Thanks for the thorough response. I'll keep an eye out for updates on issue 301.

**Comment by MadcowD** [comment]
I just want to note that it is entirely possible to make a synchronous version of Malmo if someone wants to: Essentially, Minecraft runs in a main game loop which is a) single-threaded b) manually calls ticks. To ensure synchronicity other mods essentially make their own game loops and render pipelines by overriding the `getMinecraft().timer`. If the Malmo team is interested I suggest taking a look at ReplayMod's video rendering pipeline (both sync and async modes).

Seeing that actually a good number of researchers are hesitant to jump over to Malmo given its asynchronicity, investing in a synchronous mode for Malmo, I think this is a feature worth investigating. Furthermore, it gives more fine-grained control over the environment as many of the existing agent handlers (command handlers in particular) could actually leverage the fact that the current tick is guaranteed to be the one on which they were invoked.
