### ISSUE TITLE
SchemaHelper crashes when running multiple Minecraft instances

### ISSUE THREAD

**Issue by JannerM** [Microsoft/malmo#407]
I'm running Malmo 0.18.0 on Ubuntu 14.04 and sending commands from another machine. I've noticed that when running many instances of Minecraft at once (on different ports of course), many of them will eventually crash at [SchemaHelpher.java:101](https://github.com/Microsoft/malmo/blob/87279f65c41870c1388a275b922af16f65d82b04/Minecraft/src/main/java/com/microsoft/Malmo/Utils/SchemaHelper.java#L101). It looks like `schemaURL` is returned as null on the previous line. Judging by `schemaResourceFilename` at the time of the crash, it's trying to load MissionInit.xsd.

This problem has never occurred when running only a single instance of Minecraft at a time. I have seen this crash occur in 2 instances of Minecraft simultaneously immediately after beginning a 3rd, although it is usually not this quick. Sometimes it takes a while before crashing, but has always happened within two hours in my experience.

**Comment by DaveyBiggers** [comment]
Interesting, thanks for pointing this out.
As far as I know we've never come across this, but when we run multiple instances of Minecraft on one machine, we tend to make multiple copies of the Minecraft folder, and run one instance per copy. (We do this mainly because launchClient.sh doesn't behave well if it's run concurrently, due to the gradle build stuff that happens).
Still, the crashing code really _ought_ to be thread-safe, so I'll do some digging and see if I can get to the bottom of what's happening here.

**Comment by DaveyBiggers** [comment]
Running launchClient.sh does call gradle, which will clean and rebuild Minecraft. On Windows this seems to be safe - gradle doesn't seem to be allowed to delete any files that are currently in use - but I assume Ubuntu is a bit more flexible in this regard, and if the timing is right (or wrong), the schema files may well have been deleted at the point where SchemaHelper.java tries to access them.

The workaround mentioned above (having multiple copies of the Minecraft folder) should avoid this. The other option is to fire up all the required copies (one at a time) _before_ starting to run any missions.

Am closing this issue now, but feel free to re-open if these workarounds aren't sufficient.
