### ISSUE TITLE
Jaxb 

### ISSUE THREAD

**Issue by NIKOLAOSBEDS** [Microsoft/malmo#452]
Hello, I try to run the fill "launchClient" and I have the following error: 

Execution Field failed for task: Jaxb.
unable to parse the shema. 
![2017-01-23 2](https://cloud.githubusercontent.com/assets/25309541/22226221/38f926f0-e1ce-11e6-9516-7444c9f99b98.png)

**Comment by DaveyBiggers** [comment]
I suspect this is caused by the non-ASCII characters in your path, or the space in "Malmo install" - or possibly both. We've definitely had problems caused by spaces in the path before - eg #220 and #176. Try moving Malmo to a different location.

I'm also a little confused that you seem to have a mix of 0.19 and 0.14 in the path... are you building from source, or did you download a pre-built release? You may also need to check that your MALMO_XSD_PATH is set correctly, and is pointing to the right version.

**Comment by NIKOLAOSBEDS** [comment]
Ok. Worked now. Thanks a lot.

**Comment by DaveyBiggers** [comment]
Great, glad it's working now.
