### ISSUE TITLE
"forceReset" not working as expected

### ISSUE THREAD

**Issue by okkhoy** [Microsoft/malmo#500]
May be related to #490 

Steps are too many to describe. 
Please use the environment here: https://github.com/okkhoy/minecraft-rl.git to reproduce the issue!

This is pretty much what I use for my work as well.

In the main loop:
 - without the `sendCommand("quit")` I get an error stating mission is already running. (on both Versions 0.19 and 0.21)
 - action selection is random; but should still suffice.
 - i use a hack to force an observation being made (by using `sendCommand("jump 0")`) that can be ignored in this issue.

Please let me know if you need any additional details.

**Comment by DaveyBiggers** [comment]
Thanks for the code! Makes it much easier to debug.

forceReset is working correctly. The issue you are seeing (old blocks appearing in each episode) is actually caused by your mission code. You create your mission object in `SimpleMalmoEnvironment.__init__`:

```self.mission = MalmoPython.MissionSpec(self.mission_xml, True)```

and then you add an item to it each time the `reset()` method is called:

```self.mission.drawItem(source_loc[0], 47, source_loc[1], self.landmark_types[self.destination])```

The trouble is that this has a cumulative effect - since you never recreate the mission object, each new drawItem statement is simply appended to the previous ones. You can verify this by examining the mission XML that gets sent to Minecraft - after several episodes, this is what it looked like for me:

```
<Mission>
        <About>
            <Summary>Simple Malmo Environment</Summary>
        </About>
        <ServerSection>
            <ServerInitialConditions>
                <Time>
                    <StartTime>1</StartTime>
                </Time>
                <Weather>clear</Weather>
            </ServerInitialConditions>
            <ServerHandlers>
                <FlatWorldGenerator destroyAfterUse="true" forceReset="true" generatorString="3;7,220*1,5*3,2;3;,biome_1" seed=""/>
                <DrawingDecorator>
                    <DrawCuboid type="air" x1="0" x2="6" y1="46" y2="50" z1="0" z2="6"/>
                    <DrawCuboid type="sandstone" x1="0" x2="6" y1="45" y2="45" z1="0" z2="6"/>
                    <DrawBlock type="redstone_block" x="1" y="45" z="2"/>
                    <DrawBlock type="emerald_block" x="2" y="45" z="5"/>
                    <DrawBlock type="lapis_block" x="5" y="45" z="6"/>
                    <DrawBlock type="gold_block" x="5" y="45" z="2"/>
                    <DrawBlock type="bedrock" x="3" y="45" z="2"/>
                    <DrawBlock type="bedrock" x="3" y="46" z="2"/>
                    <DrawBlock type="bedrock" x="3" y="47" z="2"/>
                    <DrawBlock type="beacon" x="3" y="48" z="2"/>
                    <DrawBlock type="bedrock" x="4" y="45" z="2"/>
                    <DrawBlock type="bedrock" x="4" y="46" z="2"/>
                    <DrawBlock type="bedrock" x="4" y="47" z="2"/>
                    <DrawBlock type="beacon" x="4" y="48" z="2"/>
                    <DrawBlock type="bedrock" x="4" y="45" z="3"/>
                    <DrawBlock type="bedrock" x="4" y="46" z="3"/>
                    <DrawBlock type="bedrock" x="4" y="47" z="3"/>
                    <DrawBlock type="beacon" x="4" y="48" z="3"/>
                    <DrawBlock type="bedrock" x="5" y="45" z="3"/>
                    <DrawBlock type="bedrock" x="5" y="46" z="3"/>
                    <DrawBlock type="bedrock" x="5" y="47" z="3"/>
                    <DrawBlock type="beacon" x="5" y="48" z="3"/>
                    <DrawBlock type="bedrock" x="2" y="45" z="4"/>
                    <DrawBlock type="bedrock" x="2" y="46" z="4"/>
                    <DrawBlock type="bedrock" x="2" y="47" z="4"/>
                    <DrawBlock type="beacon" x="2" y="48" z="4"/>
                    <DrawBlock type="bedrock" x="3" y="45" z="5"/>
                    <DrawBlock type="bedrock" x="3" y="46" z="5"/>
                    <DrawBlock type="bedrock" x="3" y="47" z="5"/>
                    <DrawBlock type="beacon" x="3" y="48" z="5"/>
                    <DrawBlock type="bedrock" x="3" y="45" z="6"/>
                    <DrawBlock type="bedrock" x="3" y="46" z="6"/>
                    <DrawBlock type="bedrock" x="3" y="47" z="6"/>
                    <DrawBlock type="beacon" x="3" y="48" z="6"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="redstone_block" x="5" y="47" z="6"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="lapis_block" x="5" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="redstone_block" x="5" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="lapis_block" x="1" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="emerald_block" x="5" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="emerald_block" x="5" y="47" z="6"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="lapis_block" x="1" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="redstone_block" x="5" y="47" z="6"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="gold_block" x="5" y="47" z="6"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="lapis_block" x="5" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="emerald_block" x="5" y="47" z="6"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="gold_block" x="1" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="redstone_block" x="5" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="emerald_block" x="5" y="47" z="2"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="lapis_block" x="2" y="47" z="5"/>
                </DrawingDecorator>
                <DrawingDecorator>
                    <DrawItem type="emerald_block" x="1" y="47" z="2"/>
                </DrawingDecorator>
                <ServerQuitFromTimeUp description="" timeLimitMs="50000"/>
                <ServerQuitWhenAnyAgentFinishes description=""/>
            </ServerHandlers>
        </ServerSection>
        <AgentSection mode="Survival">
            <Name>ButterFingers</Name>
            <AgentStart>
                <Placement pitch="0" x="5.5" y="46" yaw="0" z="2.5"/>
                <Inventory/>
            </AgentStart>
            <AgentHandlers>
                <ObservationFromFullStats/>
                <ObservationFromFullInventory/>
                <ObservationFromDiscreteCell/>
                <ObservationFromRay/>
                <VideoProducer viewpoint="1" want_depth="false">
                    <Width>480</Width>
                    <Height>320</Height>
                </VideoProducer>
                <RewardForSendingCommand dimension="0" distribution="" reward="-1"/>
                <DiscreteMovementCommands autoFall="false" autoJump="false"/>
                <InventoryCommands/>
                <MissionQuitCommands quitDescription=""/>
            </AgentHandlers>
        </AgentSection>
    </Mission>
```

To fix this, I suggest creating a new mission object for each episode. Once this is done you should also find that the "soft reset" (ie drawing a volume of air before drawing your environment, to erase previous entities) should suffice, and you can drop the forceReset flag entirely, which will significantly speed up the turnaround between episodes.

**Comment by okkhoy** [comment]
aah! (or arrrrrgh!) i never realized this could be the issue :-( thanks for helping me debug :-D
could I just check with you, if calling `sendCommand("quit")` is still necessary, assuming `forceReset` is retained?

**Comment by DaveyBiggers** [comment]
You should never have needed the quit messages - I'm not yet clear on exactly what was going on, but there's definitely a problem with this code:

```
for retry in range(retries):
            try:
                malmo_env.startMission(self.mission, self.mission_record)
                time.sleep(8)

                world_state = malmo_env.getWorldState()
                if world_state.has_mission_begun:
                    break
            except RuntimeError as e:
                if retry == retries - 1:
                    log.error("Error starting mission. Max retries elapsed. Closing! %s", e.message)
                    exit(1)
                else:
                    time.sleep(2.5)

        world_state = malmo_env.getWorldState()

        while not world_state.has_mission_begun:
            log.debug("Waiting for mission to begin")
            time.sleep(0.1)
            world_state = malmo_env.getWorldState()
            for error in world_state.errors:
                log.error("Error: %s", error.text)
```
If the mission takes longer than 8 seconds to start (which it almost always does on my machine) then the check for `if world_state.has_mission_begun` will fail, and the code will loop back round and call `startMission` again.
`startMission` will then fail with a "no client available" exception, since the Minecraft client is busily setting up, building the terrain etc. Your code will sleep for 2.5 seconds, and then call `startMission` for the third and final time.
This time, you'll either get the "no client available" exception again (if Minecraft is still setting up), or, more likely, you'll get the "mission already running" exception that you were seeing, and the script will exit.

What I don't understand is why adding the "quit" command would have fixed this for you - it doesn't fix it for me, and I can see no reason why it would. Bizarre.

I rewrote this code to be more like what we do in the python samples, and removed the quit messages, and everything worked fine for me.

One other note: you are positioning your agent at the corner of a square, not in the centre - Minecraft co-ords work such that the boundaries of the squares are integer values, and the centres are at (x+0.5,z+0.5). This might also be throwing your experiment - and it certainly leads to occasional death-by-suffocation, since you're occasionally placing the agent's centre-point on the corner of a wall.

**Comment by DaveyBiggers** [comment]
Ah - I see the problem with the "mission already running" error - you are starting a new mission before the old one has actually completed. You have defined your own episode end conditions here:
```
while i < n_steps_per_ep and not terminal:
```
but as far as Malmo is concerned, the mission is still running, and any attempt to launch a new mission will fail.

You can either send the quit command, as you were doing (though it seems cleaner to do this after your exit condition, rather than before each new mission), but a better way would be to use Malmo's quit handlers.
For example, `AgentQuitFromReachingCommandQuota` should take care of the n_steps_per_ep for you - you can specify that an agent is only allowed to carry out a certain number of actions before the episode ends. There's also an `AgentQuitFromCollectingItem`, which might simplify your code - it will end the episode when the agent collects the specified item.

**Comment by okkhoy** [comment]
I think I can use `AgentQuitFromReachingCommandQuota` in lieu of `while i < n_steps_per_ep and not terminal`; I believe in that case, there would be no need to call `sendCommand("quit")`. I cannot use `AgentQuitFromCollectingItem` since collecting item is just one part of the problem.

Also, thank you for pointing this:
>One other note: you are positioning your agent at the corner of a square, not in the centre - Minecraft co-ords work such that the boundaries of the squares are integer values, and the centres are at (x+0.5,z+0.5). This might also be throwing your experiment - and it certainly leads to occasional death-by-suffocation, since you're occasionally placing the agent's centre-point on the corner of a wall.

I think now I know why the agent was dying some times :-|
