### ISSUE TITLE
Python tutorial files don't work... Strange error messages

### ISSUE THREAD

**Issue by EnricoDelPiero** [Microsoft/malmo#550]
Hello, 
I'm getting different error messages...
When I am trying to run the python tutorials i see this:
C:\Users\Heinrich Peters\Desktop\Malmo\Builds\Malmo-0.22.0-Windows-64bit\Malmo-0.22.0-Windows-64bit\Python_Examples>python tutorial_1.py
Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.

The also the Minecraft log shows these errors:
[15:51:57] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[15:51:58] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing

in #206 the person said it was fixed by not opening a singleplayer game before launcing the agent. 
However, i havent opened a game and im getting the same error messages. 

Do you have an idea what i can try?
Many thanks in advance.

**Comment by awscodu** [comment]
Before you can run the python tutorial, you must first launch the launchClient.bat from the C:\...\Malmo-0.22.0-Windows-64bit\Minecraft folder in a separate command prompt. This will build the minecraft client that Malmo uses for input/output. 

Currently we are experiencing errors with this batch file, because it cannot retrieve the files from minecraftforge.net to build the client.

https://github.com/Microsoft/malmo/issues/547

**Comment by EnricoDelPiero** [comment]
thank you for your answer.
however, ive always been running the bat file first, so that cannot be the solution.
the error messages also pup up in the command prompt that is running the launchclient batch file.
any other ideas?

**Comment by awscodu** [comment]
> the error messages also pup up in the command prompt that is running the launchclient batch file.
What do the error messages say? If the .bat file fails to build the client you cannot run the tutorial.

**Comment by awscodu** [comment]
#547

**Comment by EnricoDelPiero** [comment]
The message from the cmd the launchclient.bat was run in look like this:
[15:51:57] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[15:51:58] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing

**Comment by DaveyBiggers** [comment]
Those FML messages are harmless - they always happen. Does a Minecraft window appear? If so, you should be able to run the tutorial.
I think the error in #206 was caused by the user manually starting a game in the Minecraft window, and then attempting to run the tutorial. Just to clarify - you should only need to run launchClient.bat, wait until a Minecraft window appears, and then run the tutorial.

If this still doesn't work, you may have some issues with the default port - Malmo uses port 10000 as a default. (This can be changed, but most of the tutorials/samples just assume 10000 is okay.) You can check which port your Minecraft instance is using by going to the Mods menu screen and finding Malmo in the list - it should look something like this:

![image](https://user-images.githubusercontent.com/13402052/26984510-8b784224-4d37-11e7-8d00-bc3265cc2974.png)

**Comment by EnricoDelPiero** [comment]
Thank you very much.
I did everything according to your description. 
However, the problem was eventually solved by setting up a new user account on my computer 💃

**Comment by maxisbest** [comment]
my malmo uses port 10001. 
if I run python examples' tutorial_1.py, how can I talk to my mod? 
should I change _agent_host = MalmoPython.AgentHost()_ to 
**agent_host = MalmoPython.AgentHost('localhost:10001')** ? 
but it failed.
many thanks.

**Comment by DaveyBiggers** [comment]
Glad this is working for everyone now (though I'm not sure why Henry had to set up a new user account!?).
