### ISSUE TITLE
Leftover Structures Clutter up Maps

### ISSUE THREAD

**Issue by EnricoDelPiero** [Microsoft/malmo#554]
Hi there, 
Everytime i rerun my script there are leftover structures from previous iterations. 
Most blocks (but not all) that were placed in a specific iteration just remain in the environment. 
They only disappear when i relaunch the client, which is really annoying. 

Does anybody have a solution for that kind of problem? 
Can i clean up the environment at the start or end of each iteration?
I know that the BuildBattleDecorator would clear up the designated area between its runs. How does that work?
A related problem is this: Time and distance travelled do not reset with each iteration, which makes the information basically useless. 
I would be super thankful for a solution.
Best,
Henry

**Comment by DaveyBiggers** [comment]
Hi Henry, this is by design (see eg the note in section 5 of the tutorial).
The usual approach to removing leftover structures is to "erase" them by using the drawing decorator to draw a volume of air on top of them. You will find this technique used in many of the python samples.
See also #490.

As for time and distance, I suggest you grab the values at the start of each episode, and use them as offsets. Minecraft tracks these achievements per player, and won't reset them unless the player gets reset (eg dies and respawns).
Hope that helps,
Dave.

**Comment by EnricoDelPiero** [comment]
Thank you Dave, very helpful!
