### ISSUE TITLE
Forge Mod Loader detected missing blocks/items

### ISSUE THREAD

**Issue by alyssa-adams** [Microsoft/malmo#565]
In Malmo-0.30, when starting a mission that loads the world from a file that was saved under Malmo-0.21 or earlier, loading fails with this message:

![image](https://user-images.githubusercontent.com/9851523/27484863-a657ac74-5822-11e7-968b-15c00a1481db.png)

**Comment by DaveyBiggers** [comment]
Turns out the _item_ form of lit_furnace was removed in MC1.9, since it's unused. (The block form remains, which makes sense - it's possible to have a lit furnace placed in the world as a block, but it's not possible to carry a lit furnace around as an item in your inventory.)
So this message is harmless from the Minecraft perspective - see http://www.minecraftforge.net/forum/topic/39250-forge-mod-loader-detected-missing-blocksitems-minecraftlit_furnace/ - but having the gui pop up breaks Malmo. Will try to find a way round this.

**Comment by DaveyBiggers** [comment]
Fixed in aa5529148f66ac5980d8af7b9858a1694eb6b897
