### ISSUE TITLE
How to get the goal position in ClassroomDecorator?

### ISSUE THREAD

**Issue by JunhongXu** [Microsoft/malmo#599]
I would like to hard coded an agent that navigates to a goal position using observations (not RGB pixels).

1. How to get the goal position of ClassroomDecorator?

2. How to hard code which actions to take after getting this goal position?

One possible solution I am thinking of is just not using ClassroomDecorator, but instead writing an XML that indicates a goal position by myself.

**Comment by DaveyBiggers** [comment]
I'm afraid there's currently no way to get the goal position from the ClassroomDecorator.
See also the MazeDecorator, which suffers from a similar problem - though it _can_ feed you directions to the goal via an observation - check out MazeRunner.py which demonstrates this.

Otherwise, your approach is good - create your own environment in XML, that way you have complete control over the positioning of the goal.

You can also find the goal square yourself using the grid observation, though for large mazes / classroom setups it will add some overhead, since it currently returns all the blocks in the specified volume with every observation.

**Comment by DaveyBiggers** [comment]
Am closing this, but please feel free to share your progress, or re-open if you still have questions.
