### ISSUE TITLE
Unable to run Malmo headless on Ubuntu

### ISSUE THREAD

**Issue by vivekveeriah** [Microsoft/malmo#601]
Hi, I am trying to run Malmo headless on a Ubuntu server (without gui). It has cuda-8 installed with opengl-libs. I have already tried the steps referenced in #291 and in #535, but nothing has worked yet. Here is the crash report that I got.

[crash-2017-10-11_10.19.14-client.txt](https://github.com/Microsoft/malmo/files/1375913/crash-2017-10-11_10.19.14-client.txt)

**Comment by DaveyBiggers** [comment]
We've seen problems with incompatibility between cuda and opengl - you need to install the nvidia drivers using the --no-opengl-files flag, otherwise xvfb will fail to run. There are a few articles about this on the internet - eg https://davidsanwald.github.io/2016/11/13/building-tensorflow-with-gpu-support.html
If your problem is the same, then you might need to de-install your nvidia drivers and then reinstall them with --no-opengl-files. I did this on an Ubuntu machine and it was relatively painless - I think I did something along these lines - https://gist.github.com/8enmann/931ec2a9dc45fde871d2139a7d1f2d78 

Let us know if this helps.

**Comment by vivekveeriah** [comment]
Yes, reinstalling nvidia drivers without opengl libs works! Thanks!

**Comment by DaveyBiggers** [comment]
Great! Thanks for letting us know.

**Comment by vivekveeriah** [comment]
Hi,
Now I get a error: "no OpenGL context found" on a different ubuntu machine with cuda-8 libs. However, the cuda was installed without opengl-libs. Here is the crash report.
[crash-2017-10-13_09.27.02-client.txt](https://github.com/Microsoft/malmo/files/1382738/crash-2017-10-13_09.27.02-client.txt)

**Comment by qizhg** [comment]
@vivekveeriah Have you solved this?

**Comment by SamNPowers** [comment]
I'm having the same issue, though it's not quite consistent. It would be helpful for me, on the particular environment I'm on, to be able to specifically point Minecraft to a particular libGL.so. Is there a recommended way to do this, to ensure it's picked up? (Environment variable, gradlew setup change, etc.)
