### ISSUE TITLE
Observation from mods?

### ISSUE THREAD

**Issue by axhue** [Microsoft/malmo#610]
Hey guys,

So I wanted to try add thirst into my environment, is it possible to observe other stats from mods? If so, does Malmo support using a newer Forge loader? would I need to build from source?

Thanks!

**Comment by DaveyBiggers** [comment]
Malmo wasn't designed to work alongside other mods, and won't be tested against other mods - but there's no particular reason why this wouldn't work, assuming the other mods don't conflict with Malmo at all. If you already run a modded Minecraft, you should be able to drop Malmo into your mods folder in the normal way - you can find the jar in your Malmo installation, inside Minecraft/build/libs.

To return observations from other mods, you'd need to fork the Malmo code-base and add your own code to do this. The simplest approach would be to add code to `ObservationFromFullStatsImplementation` (which calls through to methods in `JSONWorldDataHelper`). You should only need to rebuild the mod if you do it this way; the rest of Malmo should work as is. We're unlikely to accept this as a pull request since we don't want to support other mods, but you should be able to get something working for your own purposes.
