### ISSUE TITLE
No v0.31.0 for macOS

### ISSUE THREAD

**Issue by mtyn** [Microsoft/malmo#623]
There doesn't seem to be a build of v0.31.0 for MacOS? Is this something that is going to be added or do we need to build from source to use Python 3 on Mac? Thanks.

**Comment by N14LL** [comment]
Have you tried using the CentOS precompiled download? It works on my mac and along with a couple of others I've spoken to, and whilst its a Unix build, it can just be installed in the same way as a normal mac build - i.e. through ./launchClient.sh   on terminal

(although I have had a couple of issues with extensions, but thats purely down to my machine config and not Malmo itself)

**Comment by merithayan** [comment]
Thanks for the reply, I have tried using the CentOS build, and while the client works I get module errors when using the python examples. This is no longer an issue for myself as I have used the older version and Python 2.7 for the project I was working on, so I haven't looked into it further - it could well be due to a problem with my machine config that the CentOS python examples aren't working for me.

**Comment by Phantomb** [comment]
The module error might be either because there is some version mismatch with the python version you have installed, or it might be that Malmo cannot be found (is the path set correctly? Another option is to make sure that there is a MalmoPython.so file in the same folder). What is the exact error you get?

**Comment by N14LL** [comment]
@merithayan - I see you're a GU student too (just thought i would check given you said the project had finished & saw GUTS Hackathon commits mentioned!); so going to assume you're also in Bjørn's AI class (I'm one of the MSc students!)! If thats the case, good luck with your demo!

We actually ended up running in python 2.7 for our final tests & demo also just due to the team member's machine we decided to run all the tests on having a clean install of it with only the couple of external libraries we used (Matlibplot & Pytorch). It worked fine with python 3, but any difference was negligible.

Thanks for the assist to @Phantomb - I think you're probably correct on the mismatch of either version or path, as the majority of mac errors i've seen have been down to this so certainly worth noting for anyone else running into issues with it.

**Comment by akzaidi** [comment]
I'm hitting the same issue on macOS while trying to run the 0.31 centOS binaries. Able to render the client, but unable to run any missions from python:

```bash
➜  Python_Examples /usr/bin/python run_mission.py
Traceback (most recent call last):
  File "run_mission.py", line 22, in <module>
    import MalmoPython
ImportError: dlopen(/Users/azaidi/MalmoPlatform/Python_Examples/MalmoPython.so, 2): no suitable image found.  Did find:
	/Users/azaidi/MalmoPlatform/Python_Examples/MalmoPython.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
```

**Comment by carl24k** [comment]
@merithayan : would you please tell me which version you got working on Mac with python 2.7 (and what version of mac you are on)?  I've so far been unable to get either the pre-built to work or build an executable that passes the tests on Mac.   (I'm on Os X 10.12.6, which seems to have python 2.7.10 for the system, following the advice to use system python...  i haven't upgraded to the latest OS X, but I would if I thought it might make Malmo work; holding off since an OS upgrade might make Malmo less likely to work for all I know... ;-)

**Comment by merithayan** [comment]
@carl24k I got the mac release of version 30 working on mac with Python 2.7 installed from the Python website, with dependencies installed in a virtual environment. I couldn't get the system python to work on 10.13, due to a issue with the rootless system preventing python updates, but I was using some extra libraries that wern't part of the malmo distribution (the AIMA toolbox).

**Comment by AndKram** [comment]
More recent versions available.
