### ISSUE TITLE
Agent sometimes moving sideways (strafing) when issued (discrete) command `move 1`

### ISSUE THREAD

**Issue by Phantomb** [Microsoft/malmo#690]
In some runs, the agent walks sideways (i.e. strafing, and as far as I have seen, always to the right) when issued the `move 1` command. This will happen multiple times in a row. In a next episode (or maybe even in the same, it's hard to tell) the `move 1` command might properly move it forward again.

This is using `DiscreteMovementCommands` with `autofall`. When the agent is initialized, it is placed using a random yaw like so:
```python
turn_direction = random.randint(0, 3) * 90
self.agent_host.sendCommand('chat /tp Agent ' + str(x) + ' ' + str(y) + ' ' + str(z) + ' ' + str(turn_direction) + ' 0.0')
```

I notice this behaviour on multiple machines, both Windows and Ubuntu 16.04, and when training on different domains. 

Might this have something to do with the way I set the yaw at the start? Or a turn not registering? I am not really overclocking malmo to any extent. Is it related to #255?

**Comment by DaveyBiggers** [comment]
I suspect it's something to do with the way you are setting the yaw, yes, though the code should be calculating the direction from the player's current yaw. How quickly after sending the tp command do you start sending move commands? I wonder if it just takes Minecraft a while to apply the teleport?

You can set the initial yaw in the Mission XML, rather than by sending a command - does this work?
Failing that, you could send a random number of turn commands, rather than the chat command.

**Comment by Phantomb** [comment]
Do you reckon that using the [`mission.startAtWithPitchAndYaw()`](http://microsoft.github.io/malmo/0.30.0/Documentation/classmalmo_1_1_mission_spec.html#a1bfe8e833c9462cfefa4617d333f0bd6) might alleviate this problem? If so, I'll use that.

**Comment by Phantomb** [comment]
Using `mission.startAtWithPitchAndYaw()`, I have not seen the issue again yet, so that seems to have fixed it.  I'll report here if I spot it happening again.
